;[
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    discount_price: 15.99,
    imageUrl: "https://example.com/great_gatsby.jpg",
    description: "A novel depicting the American Dream in the 1920s.",
    actual_price: 19.99,
    percentage_off: 20,
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    discount_price: 12.49,
    imageUrl: "https://example.com/to_kill_a_mockingbird.jpg",
    description: "A story about racial injustice in the American South.",
    actual_price: 14.99,
    percentage_off: 17,
  },
  {
    title: "1984",
    author: "George Orwell",
    discount_price: 9.99,
    imageUrl: "https://example.com/1984.jpg",
    description: "A dystopian novel portraying a totalitarian regime.",
    actual_price: 12.99,
    percentage_off: 23,
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    discount_price: 11.79,
    imageUrl: "https://example.com/catcher_in_the_rye.jpg",
    description: "A story of teenage angst and alienation.",
    actual_price: 13.99,
    percentage_off: 16,
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    discount_price: 8.99,
    imageUrl: "https://example.com/pride_and_prejudice.jpg",
    description: "A classic romantic novel set in the 19th century.",
    actual_price: 10.99,
    percentage_off: 18,
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    discount_price: 14.59,
    imageUrl: "https://example.com/the_hobbit.jpg",
    description: "A fantasy adventure novel in Middle-earth.",
    actual_price: 17.99,
    percentage_off: 19,
  },
  {
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    discount_price: 20.49,
    imageUrl: "https://example.com/lotr.jpg",
    description: "An epic high-fantasy trilogy.",
    actual_price: 24.99,
    percentage_off: 18,
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    discount_price: 10.29,
    imageUrl: "https://example.com/the_alchemist.jpg",
    description: "A novel about finding one's destiny.",
    actual_price: 12.99,
    percentage_off: 21,
  },
  {
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    discount_price: 9.79,
    imageUrl: "https://example.com/harry_potter.jpg",
    description: "The first book in the Harry Potter series.",
    actual_price: 11.99,
    percentage_off: 18,
  },
  {
    title: "The Da Vinci Code",
    author: "Dan Brown",
    discount_price: 13.49,
    imageUrl: "https://example.com/da_vinci_code.jpg",
    description: "A mystery thriller involving religious symbology.",
    actual_price: 15.99,
    percentage_off: 16,
  },
]
